services:
  "gitlab.example.com": "gitlab:gitlab.example.com" # add custom GitLab instance
git:
  paging:
    colorArg: always
    pager: diff-so-fancy
os:
  editCommand: "nvim"
  editCommandTemplate: "{{editor}} +{{line}} -- {{filename}}"
  openCommand: 'tmux new-window -c "#{pane_current_path}" nvim -- {{filename}}'
