#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json
cache = true

[default_session]
name = "dotfiles"
path = "~/.dotfiles"

[[session]]
name = "nvim-config"
path = "~/.config/nvim"
startup_command = "nvim"

[[wildcard]]
name = "Squiz"
pattern = "~/dev/Squiz/**"
startup_command = "fnm use default && nvim"
windows = [ "node" ]

[[session]]
name = "Downloads"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "Trash"
path = "~/.Trash"
startup_command = "yazi"

[[window]]
name = "nvim"
startup_script = "fnm use default && nvim"

[[window]]
name = "node"
startup_script = "fnm use"
