#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json
cache = true

[tui]
prompt = "⚡ "
placeholder = "Pick a sesh…"
show_icons = true
show_windows = true
preview = false
alias_auto_connect_delay = "250ms"
alias_filter_prefix = ";"

[[session]]
name = "dotfiles"
path = "~/.dotfiles"
alias = "df"
alias_auto_connect = true

[[session]]
name = "nvim-config"
path = "~/.config/nvim"
alias = "nv"
alias_auto_connect = true
startup_command = "nvim"

[[session]]
name = "Squiz"
path = "~/dev/Squiz"
alias = "sq"
alias_auto_connect = true

[[wildcard]]
name = "Squiz"
pattern = "~/dev/Squiz/**"
startup_command = "fnm use default && nvim"
windows = [ "node" ]

[[session]]
name = "Downloads"
path = "~/Downloads"
alias = "dl"
alias_auto_connect = true
startup_command = "yazi"

[[session]]
name = "Trash"
path = "~/.Trash"
startup_command = "yazi"

[[window]]
name = "nvim"
startup_script = "fnm use default && nvim"

[[window]]
name = "node"
startup_script = "fnm use"
