-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
-- List current monitors and supported resolutions with: hyprctl monitors all

local omarchy_gdk_scale = 1
local omarchy_monitor_scale = 1

hl.env("GDK_SCALE", tostring(omarchy_gdk_scale))
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = omarchy_monitor_scale })

-- From the old monitors.conf (generated by hyprmoncfg).
-- Dell primary at 0,0; Daewoo mini-monitor below-right at 600x1080.
hl.monitor({
  output = "desc:Daewoo Electronics Company Ltd CL07-HDMI 1901001",
  mode = "1024x600@59.82",
  position = "600x1080",
  scale = 1,
})
hl.monitor({
  output = "desc:Dell Inc. DELL U2422HE 37YPNM3",
  mode = "1920x1080@60.00",
  position = "0x0",
  scale = 1,
})

-- Portrait/rotated secondary monitor (transform: 1 = 90°, 3 = 270°).
-- hl.monitor({ output = "DP-2", mode = "preferred", position = "auto", scale = 1, transform = 1 })
